apiVersion: v2
name: think-watch
description: Enterprise AI API Gateway & MCP Management Platform
type: application
version: 1.0.1
appVersion: "1.0.1"
keywords:
  - ai
  - gateway
  - mcp
  - gateway
