//! OpenAPI spec ↔ route table contract.
//!
//! `/api/openapi.json` is generated by utoipa from `#[utoipa::path]`
//! macros stamped on each handler. A handler can be removed from the
//! router without removing the macro (and vice versa), and neither
//! the compiler nor the existing test suite catch the drift.
//! The result: Swagger UI happily lists endpoints that 404 in
//! production, or hides ones that work.
//!
//! This test pulls the live spec, walks every documented (path,
//! method) pair, and asserts the route exists in the running app.
//! "Exists" means the request returns *anything but 404* — 401 /
//! 403 / 405 / 422 are all fine: the route is registered, the
//! handler ran. 404 alone signals a missing route.
//!
//! What it doesn't try to do: validate response payloads against
//! the documented schema. utoipa generates schemas from the Rust
//! types via `ToSchema`, so they're already structurally tied to
//! the code; per-endpoint shape regressions are pinned in the
//! per-feature integration tests.

use serde_json::Value;
use think_watch_test_support::prelude::*;

#[ignore = "integration test — run via `make test-it`"]
#[tokio::test]
async fn openapi_spec_lists_paths_and_documents_auth_security_scheme() {
    let app = TestApp::spawn().await;
    let admin = fixtures::create_admin_user(&app.db).await.unwrap();
    let con = app.console_client();
    con.post(
        "/api/auth/login",
        json!({"email": admin.user.email, "password": admin.plaintext_password}),
    )
    .await
    .unwrap()
    .assert_ok();

    let resp = con.get("/api/openapi.json").await.unwrap();
    resp.assert_ok();
    let spec: Value = resp.json().expect("openapi.json must parse as JSON");

    // Top-level shape: OpenAPI 3.x with info.{title,version} and a
    // non-empty paths object. A regression that swaps utoipa for a
    // hand-rolled emitter and forgets `info` would fail loudly here.
    assert!(
        spec["openapi"]
            .as_str()
            .is_some_and(|v| v.starts_with("3.")),
        "openapi field must be 3.x, got {:?}",
        spec.get("openapi")
    );
    assert!(spec["info"]["title"].as_str().is_some());
    assert!(spec["info"]["version"].as_str().is_some());

    let paths = spec["paths"]
        .as_object()
        .expect("paths object missing from spec");
    assert!(
        paths.len() >= 30,
        "spec should document ≥30 paths, got {}",
        paths.len()
    );

    // The bearer/cookie security scheme must be documented — without
    // it the Swagger "Authorize" button does nothing and the spec
    // misrepresents how every protected endpoint is gated.
    let schemes = spec["components"]["securitySchemes"]
        .as_object()
        .expect("components.securitySchemes is part of the public contract");
    assert!(
        schemes.values().any(|v| v["type"] == "http"
            && v["scheme"]
                .as_str()
                .is_some_and(|s| s.eq_ignore_ascii_case("bearer"))),
        "expected an http+bearer security scheme in: {schemes:#?}"
    );
}

#[ignore = "integration test — run via `make test-it`"]
#[tokio::test]
async fn every_documented_path_is_actually_routed() {
    let app = TestApp::spawn().await;
    let admin = fixtures::create_admin_user(&app.db).await.unwrap();
    let con = app.console_client();
    con.post(
        "/api/auth/login",
        json!({"email": admin.user.email, "password": admin.plaintext_password}),
    )
    .await
    .unwrap()
    .assert_ok();

    let spec: Value = con.get("/api/openapi.json").await.unwrap().json().unwrap();
    let paths = spec["paths"].as_object().unwrap();

    // Walk every (path, method) pair. Non-route methods on the same
    // path are also enumerated under the same path object.
    let mut missing: Vec<(String, String)> = Vec::new();
    let mut total = 0u32;
    for (path_template, ops) in paths {
        let Some(ops_obj) = ops.as_object() else {
            continue;
        };
        for method in ["get", "post", "put", "patch", "delete"] {
            if !ops_obj.contains_key(method) {
                continue;
            }
            // utoipa's path templates use `{name}` placeholders;
            // substitute representative dummy values so the
            // axum router can match the request.
            let probe = substitute_path_params(path_template);
            total += 1;
            let resp = match method {
                "get" => con.get(&probe).await,
                "delete" => con.delete(&probe).await,
                "post" => con.post(&probe, json!({})).await,
                "put" => con.put(&probe, json!({})).await,
                "patch" => con.patch(&probe, json!({})).await,
                _ => unreachable!(),
            }
            .unwrap();
            // 404 alone is ambiguous:
            //   - axum returns 404 with an empty body when the
            //     route table has no match. THAT is the regression
            //     we want to catch (utoipa lists an endpoint that
            //     was never wired into the router).
            //   - a handler can also return 404 via
            //     `AppError::NotFound` — the route IS registered,
            //     but our dummy UUID didn't resolve to a real row.
            //     That's the expected runtime behaviour.
            // The two are distinguishable by the body shape:
            // `AppError::NotFound` always serialises as
            // `{"error":{"type":"not_found",...}}`, while axum's
            // default fallback body is empty. Treat the empty-body
            // 404 as the only failure case.
            if resp.status.as_u16() == 404 {
                let body = resp.text();
                let is_handler_emitted = body.contains("\"not_found\"")
                    || body.contains("\"forbidden\"")
                    || body.contains("\"bad_request\"");
                if !is_handler_emitted {
                    missing.push((method.to_uppercase(), probe));
                }
            }
        }
    }
    assert!(
        missing.is_empty(),
        "{} of {total} documented paths are not routed: {missing:?}",
        missing.len()
    );
}

/// Replace `{name}` segments with a UUID literal — every templated
/// path in this codebase uses `{id}` or `{user_id}` style names that
/// the handlers parse as `Path<Uuid>`. A non-existent UUID surfaces
/// as 404 *from the handler body* (after the route matched), which
/// would be a false positive for "route missing", so we deliberately
/// pass a syntactically valid UUID; the router accepts the path
/// regardless of whether any row matches.
fn substitute_path_params(template: &str) -> String {
    let mut out = String::with_capacity(template.len());
    let mut chars = template.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '{' {
            // skip until '}'
            for c2 in chars.by_ref() {
                if c2 == '}' {
                    break;
                }
            }
            // 00000000-0000-0000-0000-000000000000 parses as uuid::Uuid
            // and avoids colliding with anything real in the test DB.
            out.push_str("00000000-0000-0000-0000-000000000000");
        } else {
            out.push(c);
        }
    }
    out
}
